### ISSUE TITLE
shift_double_ended throws away unexpected data variables

### ISSUE THREAD

**Issue by klapo** [dtscalibration/python-dts-calibration#104]
**Is your feature request related to a problem? Please describe.**
I find this printed message unnecessary and clutters output.
`shift_double_ended` prints the message:
`I dont know what to do with the following data [data_var]`

An example of this behavior can be seen in the last cell of the example notebook `11Merge_single_measurements_into_double.ipynb`

```
ds = ds.sel(x=slice(-10, cable_length + 10))

shift1, shift2 = suggest_cable_shift_double_ended(ds.isel(time=[0,-1]).compute(),
                                                  np.arange(-10, 10, 1, dtype=int))

ds = shift_double_ended(ds, shift1)
```
which then prints the above message a handful of times.

**Describe the solution you'd like**
Requiring the user to sanitize datastore objects to only have expected fields is totally acceptable, but since the documentation states that it will only return the back scatter intensities the printed message is unnecessary. 

**Describe alternatives you've considered**
My preference would be that `shift_double_ended` accepts a list of forward and reverse datavariables or allows the use of a dimension labeling the channel so I can shift an arbitrary variable. For instance aligning the single-ended calibrated temperatures for a double-ended configuration could have some utility.

**Additional context**
I can reproduce this behavior on version 1.0.0. for my own examples.

**Comment by BSchilperoort** [comment]
Hi Karl, having the function print to the console all the time without a way to silence it is indeed a bit annoying. I think a `silent` kwarg could be added to skip the print.

I believe the function only drops the variables which have an `x` dim. The reason for this is that there is no perfect way to shift them without any extra information. The `shift_double_ended` function only shifts the `rst` and `rast` variables in the x-dimension.
I think the alternative would be to keep the variables instead of dropping them, and just trimming them to the new size of `x`.

The features you would want are indeed useful, but are outside of the original scope of `shift_double_ended`. If we would implement this, this could be a new function such as `shift_var_x` which can shift a certain variable along the x dimension.

**Comment by klapo** [comment]
I'll sketch up a working version of `shift_var_x` function and post it here.

**Comment by BSchilperoort** [comment]
#109 adds the 'verbose' kwarg for `shift_double_ended`. Setting `verbose` to False will silence the output.
