### ISSUE TITLE
Acquisition time may be checking the wrong variable

### ISSUE THREAD

**Issue by klapo** [dtscalibration/python-dts-calibration#106]
**Describe the bug**
The example notebooks all have a perfectly uniform acquisition time. i.e., always a perfect round number of seconds. However, the Ultima and XT both have acquisition times that vary with something inside the instrument.  That suggests to me that you are using the `acquisitionTime` reported in the `channelConfiguration` and not the acquisitionTime reported immediately after the data, which reports the actual duration of the measurement. If that is the case, then the `acquisitionTime` will always be uniform for a given configuration.

The reason this seems like a bug is that the `datastore_utils.check_timestep_allclose` check used by some functions allows for a 1% variation. The variation is not possible with the `channelConfiguration` `acquistionTime`.

If this is the intended behavior, then the `check_timestep_allclose` should actually be looking for non-zero differences in the acquisition time dimension as that would mean the user adjusted the time step of the configuration file.

**To Reproduce**
Not relevant for this case (I think?).

**Expected behavior**
I put the expected acquisition time into our xarray Datasets as a pandas time string, e.g., '3s' since the finalized datasets are interpolated to a uniform time stamp. I would love to be able to skip creating an acquisition time dimension filled with uniform numpy.timedeltas by providing this scalar. Similarly, I would like to be able to skip the `check_timestep_allclose` since this has posed some integration issues for me.

Alternatively, since the confidence intervals are sensitive to variations in the observing interval would it make more sense to check the time varying `acquisitionTime`?  

I understand if this is not something you want to adjust.

**Comment by BSchilperoort** [comment]
Hi Karl,

I believe we do use the `acquisitionTime` reported after the data. The location in the xml tree we use is: ('log', 'customData', 'acquisitionTime'). We might round it down to the nearest second though, but I'm not sure about that....

The reason to round down is that there are some bugs in Silixa's code related to the timestamps. If you set the machine to a 20 second acquisition time, the acquisition time of the measurements really is 20,000 ms.
However, if you look at the [this xml file](https://github.com/dtscalibration/python-dts-calibration/blob/master/tests/data/silixa_v4.5/channel%203_20151002060301031.xml), it states the acquisition time is 20.3 seconds. This is the `maxDateTimeIndex` subtracted from the `minDateTimeIndex`, and not the true acquisition time, but the acquisition + processing time. At least, this is what I've been told by Silixa!

If we do round down, and still allow for a 1% variation, that would indeed be unnecessary. However, the package also has to support other devices/manufacturers, so it might be in the code because of that.

As for skipping `check_timestep_allclose`, you can do this by setting all `acquisitionTime` values to e.g. 1 second, or adding such a variable with uniform values to the DataStore object (as you already stated). This effectively skips the checks. Our reason for including it is to check for uniformity, so the variances of the Stokes values are of only one uniform acquisition time.

**Comment by klapo** [comment]
Hi Bart, so it looks like we are talking about the same `acquisitionTime`. I learned something about the Ultima! I assumed that the observation interval really was between those two times. I'll proceed with the solution of creating an array of identical np.timedelta64 objects.
