### ISSUE TITLE
change in align double-ended result between v0.8 and v1.0?

### ISSUE THREAD

**Issue by dbrakenhoff** [dtscalibration/python-dts-calibration#111]
**Describe the bug**
I'm not sure whether this is a bug or just a question. I'm attempting to align a double-ended measurement. Something seems to have changed between versions 0.8 and 1.0 and I'm not sure what it is exactly. The following two plots were made using identical scripts (besides the label names for the stokes and anti-stokes data). Something weird seems to be happening in the function suggesting the best shifts to align the data. But I'm not really sure where to start looking for the issue. So any tips/pointers/help is greatly appreciated!

v0.8:
![check_lining_up_data_ch1_v080](https://user-images.githubusercontent.com/6552225/82818179-9c265280-9e9e-11ea-9287-16b71ccbf266.png)

v1.0:
![check_lining_up_data_ch1](https://user-images.githubusercontent.com/6552225/82818199-a1839d00-9e9e-11ea-893e-58f3d11ada46.png)

**To Reproduce**
Steps to reproduce the behavior (but this might be specific to my dataset):
1. Read in Sensornet files.
2. Shift data using suggested shift (with `suggest_cable_shift_double_ended` and `shift_double_ended`.
3. Plot two lines to check lining up of reverse and forward channels: (anti-)stokes / reverse (anti-)stokes.

**Expected behavior**
I'm thinking the result of the older version looks better. Also I think the new result is probably leading to other issues during calibration.

**Additional context**
dtscalibration versions: 0.8 vs 1.0
xarray: 1.15.1
OS: Ubuntu 20.04 (though the exact same results are achieved on Windows)

**Comment by BSchilperoort** [comment]
Hi Davíd, I think the difference might be caused by the fact that in the second image the data after the end of the fiber is not removed. This random noise throws off the alignment.

The read_sensornet_files function has changed slightly, which causes the data after the end of the fiber not to be trimmed from the data fully automatically. If you use the keyword argument 'fiber_length' when loading double ended data this issue should be fixed. 'fiber_length' is the length of fiber between the two connectors entering the DTS device.

**Comment by dbrakenhoff** [comment]
I missed that change. But cool, adding the fiber_length fixes it. Looks like what I got before now. Closing the issue!
