### ISSUE TITLE
softwareVersion="Ultima: 8.1.18.0 (64bit)

### ISSUE THREAD

**Issue by zrxdaly** [dtscalibration/python-dts-calibration#146]
**Describe the bug**
xml file version 8 is up. It seems the condition doesn't accept version 8 yet. 

**To Reproduce**
1. get this xml file version 8: because xml is not support, please download the modify the suffix [channel 1_UTC_20220824_125501.866.txt](https://github.com/dtscalibration/python-dts-calibration/files/9619446/channel.1_UTC_20220824_125501.866.txt)
2. import it using read_silixa_files
3. the error : 
`IsADirectoryError: [Errno 21] Is a directory: '/' pop up`
6. if  there is multiple files: 
```
    286         dask.base.compute
    287         """
--> 288         (result,) = compute(self, traverse=False, **kwargs)
    289         return result
    290 
...
--> 427                 raise ValueError(
    428                     'Unknown version number: {}'.format(xml_version))
    429 

ValueError: Unknown version number: 8


7. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here. Package version, python version, xarray version, operating system.
```
Propose solution: 
I test it with version 7 function: `read_silixa_files_routine_v6`. It seems the function also works for this version 8 file. 
It would be nice to incorporate this.

**Comment by zrxdaly** [comment]
#144 It seems it is already reported here

**Comment by BSchilperoort** [comment]
Hi Dai, thanks for opening the issue and providing the example file.
The fix is relatively simple, and in Frank's PR (#144) you can find the line of code that fixes this issue.

I am currently working on restoring the functionality of this github repo. As soon as that is finished I will implement the Silixa v8 fix and release a new version. 

In the meantime you could use Frank's fix with: 
`pip install https://github.com/fprice111/python-dts-calibration/zipball/master --upgrade`

**Comment by BSchilperoort** [comment]
Ultima v8.1 is now supported in the new release. The release is available with pip!
