### ISSUE TITLE
Varying gain parameter between double ended channels.

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#61]
In double ended measurements with a longer integration time per channel, the measurement device's properties can vary between the measurement of each channel. E.g. the gain used in the amplification circuit varies between the forward and backward measurement.

This variation is currently assumed to be 0, and the same gain correction is used for both channels. This results in a differing and incorrect calibrated temperature.

See residual plots below, the difference in 'gain' occurs at ~4:30

![image](https://user-images.githubusercontent.com/12114825/70331254-65e90e00-183f-11ea-964d-10f0c33c5864.png)

![image](https://user-images.githubusercontent.com/12114825/70331283-74372a00-183f-11ea-8adc-6d161a61b799.png)

**Comment by bdestombe** [comment]
Currently, indeed there is a single gain _(C)_ parameter per time step, so that fits to the average of the forward and backward measurements. Plus, the integrated differential attenuation accounts for a constant difference in _C_ between the forward and backward channel measurements. I think that is a reasonable approximation for systems that make use of an optical switch in combination with a single Stokes and a single anti-Stokes detector.

If the difference in _C_ between the forward and backward channel measurements is not constant over time, due to touching or heating of one of the connectors, such a peak indeed can occur. But the uncertainty in the estimation of _C_ should show this as well, and propagate it to the confidence intervals of the temperature estimates.

In a future update that includes the ability to include matching sections and asymmetrical attenuation, it would be able to account for this variation. With this update if we can account for the difference in _C_ between the forward and backward channel measurements, and fix your example.

**Comment by BSchilperoort** [comment]
> If the difference in C between the forward and backward channel measurements is not constant over time, due to touching or heating of one of the connectors, such a peak indeed can occur. 

I do think it's more than just the change in connector behaviour; the amplifier gain used by the device plays a role as well. If this gain changes between FW and BW measurement, it causes an error as well.

For now, the advice would be that users use shorter integration times in double-ended setups to reduce the problem. But having this issue fixed would be preferable of course.

**Comment by bdestombe** [comment]
This was implemented in version 0.7.3.
